
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">  
    <modelVersion>4.0.0</modelVersion>  
    <groupId>egovframework.voice.collector</groupId>  
    <artifactId>voice-collector-x2daarjxe4</artifactId>  
    <version>0.0.1</version>  
    <packaging>jar</packaging>  
    <name>voice-collector-x2daarjxe4-RESTful-Service</name>  
    <description>voice-collector-x2daarjxe4 service</description>  
    <properties> 
        <java.version>17</java.version>  
        <maven.compiler.source>17</maven.compiler.source>  
        <maven.compiler.target>17</maven.compiler.target>  
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>  
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>  
        <maven.build.timestamp.format>yyyyMMdd-HHmmss</maven.build.timestamp.format>  
        <buildtime>${maven.build.timestamp}</buildtime>  
        <group-name/>  
        <final-name>voice-collector-x2daarjxe4</final-name>  
        <docker-registry/>  
        <docker-name/>  
        <docker-tag/>  
        <spring-profile/> 
    </properties>  
    <parent> 
        <groupId>org.springframework.boot</groupId>  
        <artifactId>spring-boot-starter-parent</artifactId>  
        <version>3.5.14</version>  
        <relativePath/> 
    </parent>  
    <dependencies> 
        <dependency> 
            <groupId>org.springframework.boot</groupId>  
            <artifactId>spring-boot-starter</artifactId>  
            <exclusions> 
                <exclusion> 
                    <groupId>org.springframework.boot</groupId>  
                    <artifactId>spring-boot-starter-logging</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency>  
        <dependency> 
            <groupId>org.springframework.boot</groupId>  
            <artifactId>spring-boot-starter-web</artifactId> 
        </dependency>  
        <dependency> 
            <groupId>com.nimbusds</groupId>  
            <artifactId>nimbus-jose-jwt</artifactId>  
            <version>10.9</version> 
        </dependency>  
        <dependency> 
            <groupId>org.projectlombok</groupId>  
            <artifactId>lombok</artifactId> 
        </dependency>  
        <dependency> 
            <groupId>org.assertj</groupId>  
            <artifactId>assertj-core</artifactId>  
            <version>3.24.2</version> 
        </dependency>  
        <dependency> 
            <groupId>com.googlecode.log4jdbc</groupId>  
            <artifactId>log4jdbc</artifactId>  
            <version>1.2</version> 
        </dependency>  
        <dependency> 
            <groupId>org.springframework.boot</groupId>  
            <artifactId>spring-boot-starter-log4j2</artifactId>  
            <exclusions> 
                <exclusion> 
                    <groupId>org.slf4j</groupId>  
                    <artifactId>slf4j-log4j12</artifactId> 
                </exclusion> 
            </exclusions> 
        </dependency>  
        <dependency> 
            <groupId>org.springdoc</groupId>  
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>  
            <version>2.8.17</version> 
        </dependency>  
        <dependency> 
            <groupId>org.springframework.boot</groupId>  
            <artifactId>spring-boot-starter-test</artifactId>  
            <scope>test</scope> 
        </dependency>  
        <dependency> 
            <groupId>org.json</groupId>  
            <artifactId>json</artifactId>  
            <version>20260522</version> 
        </dependency>  
        <dependency> 
            <groupId>com.intellij</groupId>  
            <artifactId>annotations</artifactId>  
            <version>9.0.4</version> 
        </dependency>  
        <dependency> 
            <groupId>org.springframework.boot</groupId>  
            <artifactId>spring-boot-starter-actuator</artifactId> 
        </dependency>  
        <dependency> 
            <groupId>io.micrometer</groupId>  
            <artifactId>micrometer-registry-prometheus</artifactId> 
        </dependency>  
        <dependency> 
            <groupId>org.mybatis.spring.boot</groupId>  
            <artifactId>mybatis-spring-boot-starter</artifactId>  
            <version>3.0.5</version> 
        </dependency>  
        <dependency> 
            <groupId>org.egovframe.rte</groupId>  
            <artifactId>egovframe-rte-ptl-mvc</artifactId>  
            <version>5.0.0</version> 
        </dependency>  
        <dependency> 
            <groupId>org.egovframe.rte</groupId>  
            <artifactId>egovframe-rte-psl-dataaccess</artifactId>  
            <version>5.0.0</version> 
        </dependency>  
        <dependency> 
            <groupId>org.egovframe.rte</groupId>  
            <artifactId>egovframe-rte-fdl-idgnr</artifactId>  
            <version>5.0.0</version> 
        </dependency>  
        <dependency> 
            <groupId>org.egovframe.rte</groupId>  
            <artifactId>egovframe-rte-fdl-property</artifactId>  
            <version>5.0.0</version> 
        </dependency>  
        <dependency> 
            <groupId>org.egovframe.rte</groupId>  
            <artifactId>egovframe-rte-fdl-string</artifactId>  
            <version>5.0.0</version> 
        </dependency>  
        <dependency> 
            <groupId>org.postgresql</groupId>  
            <artifactId>postgresql</artifactId> 
        </dependency>
    </dependencies>  
    <profiles> 
        <profile> 
            <id>default</id>  
            <properties> 
                <profile-name>default</profile-name> 
            </properties>  
            <activation> 
                <activeByDefault>true</activeByDefault> 
            </activation> 
        </profile>  
        <profile> 
            <id>local</id>  
            <properties> 
                <profile-name>local</profile-name> 
            </properties> 
        </profile> 
    </profiles>  
    <build> 
        <finalName>${final-name}</finalName>  
        <resources> 
            <resource> 
                <filtering>false</filtering>  
                <directory>src/main/java</directory>  
                <includes> 
                    <include>**/*.xml</include> 
                </includes> 
            </resource>  
            <resource> 
                <directory>src/main/resources</directory> 
            </resource> 
        </resources>  
        <plugins> 
            <plugin> 
                <groupId>org.apache.maven.plugins</groupId>  
                <artifactId>maven-enforcer-plugin</artifactId>  
                <version>3.0.0-M3</version>  
                <executions> 
                    <execution> 
                        <id>enforce-maven</id>  
                        <goals> 
                            <goal>enforce</goal> 
                        </goals>  
                        <configuration> 
                            <rules> 
                                <requireMavenVersion> 
                                    <version>3.0.5</version> 
                                </requireMavenVersion> 
                            </rules> 
                        </configuration> 
                    </execution> 
                </executions> 
            </plugin>  
            <plugin> 
                <groupId>org.apache.maven.plugins</groupId>  
                <artifactId>maven-compiler-plugin</artifactId>  
                <configuration> 
                    <annotationProcessorPaths> 
                        <path> 
                            <groupId>org.projectlombok</groupId>  
                            <artifactId>lombok</artifactId>  
                            <version>${lombok.version}</version> 
                        </path> 
                    </annotationProcessorPaths> 
                </configuration> 
            </plugin>  
            <plugin> 
                <groupId>org.springframework.boot</groupId>  
                <artifactId>spring-boot-maven-plugin</artifactId>  
                <executions> 
                    <execution> 
                        <goals> 
                            <goal>repackage</goal> 
                        </goals>  
                        <configuration> 
                            <mainClass>egovframework.voice.collector.Main</mainClass> 
                        </configuration> 
                    </execution> 
                </executions> 
            </plugin>  
            <plugin> 
                <groupId>org.codehaus.mojo</groupId>  
                <artifactId>exec-maven-plugin</artifactId>  
                <version>3.0.0</version> 
            </plugin>  
            <plugin> 
                <groupId>org.codehaus.mojo</groupId>  
                <artifactId>properties-maven-plugin</artifactId>  
                <version>1.0.0</version> 
            </plugin>  
            <plugin> 
                <groupId>com.spotify</groupId>  
                <artifactId>dockerfile-maven-plugin</artifactId>  
                <version>1.4.13</version>  
                <configuration> 
                    <repository>${docker-registry}</repository>  
                    <dockerfile>./src/main/docker/Dockerfile</dockerfile>  
                    <buildArgs> 
                        <JAR_FILE>${final-name}.jar</JAR_FILE>  
                        <SPRING_PROFILE>${spring-profile}</SPRING_PROFILE> 
                    </buildArgs> 
                </configuration> 
            </plugin> 
        </plugins> 
    </build>  
    <repositories> 
        <repository> 
            <id>egovframe</id>  
            <url>https://maven.egovframe.go.kr/maven/</url>  
            <releases> 
                <enabled>true</enabled> 
            </releases>  
            <snapshots> 
                <enabled>false</enabled> 
            </snapshots> 
        </repository> 
    </repositories> 
</project>
